/**
 * Enter client base — all companies with estimated labor risk factors.
 * Sources: LinkedIn, annual reports, news, CNJ benchmarks.
 * These are conservative estimates; Claude + web_search will enrich with real-time data.
 */

export const companies = [
  // ═══════════════════════════════════════
  // FINANCIAL SERVICES
  // ═══════════════════════════════════════
  {
    id: 'nubank',
    name: 'Nubank',
    sector: 'financial_services',
    segment: 'Financial Services',
    employees: 8000,
    headquarters: 'São Paulo, SP',
    states: ['SP', 'RJ', 'MG', 'PE', 'DF'],
    cargoDiversity: 6,
    multiState: 5,
    unionActivity: 3,
    operationalRatio: 0.35,
    seniorityVariance: 4,
    recentLayoffs: 5,
    mAndA: 2,
    restructuring: 4,
    privatization: 0,
    notes: 'Demissões em 2023-2024, crescimento rápido → alta rotatividade em tech e atendimento',
  },
  {
    id: 'santander',
    name: 'Santander Brasil',
    sector: 'financial_services',
    segment: 'Financial Services',
    employees: 55000,
    headquarters: 'São Paulo, SP',
    states: ['SP', 'RJ', 'MG', 'RS', 'PR', 'BA', 'PE', 'CE', 'DF', 'SC', 'GO', 'ES'],
    cargoDiversity: 8,
    multiState: 10,
    unionActivity: 9,
    operationalRatio: 0.55,
    seniorityVariance: 8,
    recentLayoffs: 4,
    mAndA: 3,
    restructuring: 5,
    privatization: 0,
    notes: 'Bancários com sindicato muito forte (CONTRAF), fechamento de agências, digitalização',
  },
  {
    id: 'itau',
    name: 'Itaú Unibanco',
    sector: 'financial_services',
    segment: 'Financial Services',
    employees: 96000,
    headquarters: 'São Paulo, SP',
    states: ['SP', 'RJ', 'MG', 'RS', 'PR', 'BA', 'PE', 'CE', 'DF', 'SC', 'GO', 'ES', 'PA', 'MA'],
    cargoDiversity: 9,
    multiState: 10,
    unionActivity: 9,
    operationalRatio: 0.50,
    seniorityVariance: 9,
    recentLayoffs: 6,
    mAndA: 7,
    restructuring: 7,
    privatization: 0,
    notes: 'Maior banco privado do Brasil. Fusão Itaú+Unibanco gerou passivo trabalhista massivo. Fechamento de agências acelerado.',
  },
  {
    id: 'bradesco',
    name: 'Bradesco',
    sector: 'financial_services',
    segment: 'Financial Services',
    employees: 87000,
    headquarters: 'Osasco, SP',
    states: ['SP', 'RJ', 'MG', 'RS', 'PR', 'BA', 'PE', 'CE', 'DF', 'SC', 'GO', 'ES', 'PA'],
    cargoDiversity: 9,
    multiState: 10,
    unionActivity: 9,
    operationalRatio: 0.50,
    seniorityVariance: 9,
    recentLayoffs: 7,
    mAndA: 5,
    restructuring: 8,
    privatization: 0,
    notes: 'Reestruturação massiva 2023-2025 sob Marcelo Noronha, milhares de demissões, fechamento de agências',
  },
  {
    id: 'c6bank',
    name: 'C6 Bank',
    sector: 'financial_services',
    segment: 'Financial Services',
    employees: 5500,
    headquarters: 'São Paulo, SP',
    states: ['SP', 'RJ'],
    cargoDiversity: 5,
    multiState: 3,
    unionActivity: 2,
    operationalRatio: 0.30,
    seniorityVariance: 3,
    recentLayoffs: 6,
    mAndA: 2,
    restructuring: 4,
    privatization: 0,
    notes: 'Layoffs significativos 2023, JP Morgan como acionista',
  },
  {
    id: 'banco-volkswagen',
    name: 'Banco Volkswagen',
    sector: 'financial_services',
    segment: 'Financial Services',
    employees: 1200,
    headquarters: 'São Paulo, SP',
    states: ['SP'],
    cargoDiversity: 4,
    multiState: 2,
    unionActivity: 5,
    operationalRatio: 0.30,
    seniorityVariance: 6,
    recentLayoffs: 2,
    mAndA: 3,
    restructuring: 2,
    privatization: 0,
    notes: 'Banco cativo, ligado à VW do Brasil com sindicato metalúrgico forte',
  },
  {
    id: 'banco-pan',
    name: 'Banco Pan',
    sector: 'financial_services',
    segment: 'Financial Services',
    employees: 4500,
    headquarters: 'São Paulo, SP',
    states: ['SP', 'RJ', 'MG', 'PR'],
    cargoDiversity: 5,
    multiState: 5,
    unionActivity: 5,
    operationalRatio: 0.45,
    seniorityVariance: 5,
    recentLayoffs: 3,
    mAndA: 4,
    restructuring: 3,
    privatization: 0,
    notes: 'Controlado pelo BTG Pactual, foco em crédito consignado',
  },
  {
    id: 'agi',
    name: 'Agi (Agibank)',
    sector: 'financial_services',
    segment: 'Financial Services',
    employees: 3000,
    headquarters: 'Porto Alegre, RS',
    states: ['RS', 'SP', 'MG'],
    cargoDiversity: 5,
    multiState: 4,
    unionActivity: 4,
    operationalRatio: 0.50,
    seniorityVariance: 4,
    recentLayoffs: 3,
    mAndA: 2,
    restructuring: 3,
    privatization: 0,
    notes: 'Rede de agências físicas para público C/D, alta rotatividade de gerentes',
  },
  {
    id: 'inter',
    name: 'Inter (Banco Inter)',
    sector: 'financial_services',
    segment: 'Financial Services',
    employees: 4000,
    headquarters: 'Belo Horizonte, MG',
    states: ['MG', 'SP'],
    cargoDiversity: 5,
    multiState: 3,
    unionActivity: 3,
    operationalRatio: 0.30,
    seniorityVariance: 3,
    recentLayoffs: 4,
    mAndA: 3,
    restructuring: 3,
    privatization: 0,
    notes: 'IPO na Nasdaq, crescimento acelerado, cultura de startup',
  },
  {
    id: 'bv',
    name: 'BV (Banco Votorantim)',
    sector: 'financial_services',
    segment: 'Financial Services',
    employees: 3500,
    headquarters: 'São Paulo, SP',
    states: ['SP', 'RJ', 'MG', 'PR'],
    cargoDiversity: 5,
    multiState: 5,
    unionActivity: 5,
    operationalRatio: 0.40,
    seniorityVariance: 6,
    recentLayoffs: 2,
    mAndA: 2,
    restructuring: 2,
    privatization: 0,
    notes: 'Joint venture Votorantim + Banco do Brasil, estável',
  },
  {
    id: 'banco-mercantil',
    name: 'Banco Mercantil',
    sector: 'financial_services',
    segment: 'Financial Services',
    employees: 3000,
    headquarters: 'Belo Horizonte, MG',
    states: ['MG', 'SP', 'RJ', 'BA'],
    cargoDiversity: 5,
    multiState: 5,
    unionActivity: 5,
    operationalRatio: 0.50,
    seniorityVariance: 7,
    recentLayoffs: 3,
    mAndA: 1,
    restructuring: 3,
    privatization: 0,
    notes: 'Banco tradicional, foco em aposentados/INSS, funcionários com alta antiguidade',
  },
  {
    id: 'banco-daycoval',
    name: 'Banco Daycoval',
    sector: 'financial_services',
    segment: 'Financial Services',
    employees: 2000,
    headquarters: 'São Paulo, SP',
    states: ['SP', 'RJ'],
    cargoDiversity: 4,
    multiState: 3,
    unionActivity: 4,
    operationalRatio: 0.35,
    seniorityVariance: 5,
    recentLayoffs: 2,
    mAndA: 1,
    restructuring: 1,
    privatization: 0,
    notes: 'Middle market, estável',
  },
  {
    id: 'bmg',
    name: 'Banco BMG',
    sector: 'financial_services',
    segment: 'Financial Services',
    employees: 3500,
    headquarters: 'Belo Horizonte, MG',
    states: ['MG', 'SP', 'RJ', 'BA', 'PE'],
    cargoDiversity: 5,
    multiState: 6,
    unionActivity: 5,
    operationalRatio: 0.50,
    seniorityVariance: 6,
    recentLayoffs: 4,
    mAndA: 2,
    restructuring: 4,
    privatization: 0,
    notes: 'Crédito consignado, reestruturação digital em andamento',
  },
  {
    id: 'uol',
    name: 'UOL (PagSeguro/PagBank)',
    sector: 'financial_services',
    segment: 'Financial Services',
    employees: 7000,
    headquarters: 'São Paulo, SP',
    states: ['SP', 'RJ', 'MG', 'PR', 'SC'],
    cargoDiversity: 6,
    multiState: 6,
    unionActivity: 3,
    operationalRatio: 0.40,
    seniorityVariance: 4,
    recentLayoffs: 5,
    mAndA: 4,
    restructuring: 5,
    privatization: 0,
    notes: 'Grupo UOL/PagSeguro, layoffs em tech, múltiplas subsidiárias',
  },
  {
    id: 'omni',
    name: 'Omni',
    sector: 'financial_services',
    segment: 'Financial Services',
    employees: 1500,
    headquarters: 'São Paulo, SP',
    states: ['SP', 'RJ'],
    cargoDiversity: 4,
    multiState: 3,
    unionActivity: 4,
    operationalRatio: 0.40,
    seniorityVariance: 5,
    recentLayoffs: 2,
    mAndA: 1,
    restructuring: 2,
    privatization: 0,
    notes: 'Financeira focada em veículos',
  },
  {
    id: 'recovery',
    name: 'Recovery',
    sector: 'financial_services',
    segment: 'Financial Services',
    employees: 2500,
    headquarters: 'São Paulo, SP',
    states: ['SP', 'RJ', 'MG'],
    cargoDiversity: 4,
    multiState: 4,
    unionActivity: 3,
    operationalRatio: 0.60,
    seniorityVariance: 4,
    recentLayoffs: 3,
    mAndA: 3,
    restructuring: 3,
    privatization: 0,
    notes: 'Cobrança e recuperação de crédito, alta rotatividade de operadores',
  },
  {
    id: 'bem-promotora',
    name: 'Bem Promotora',
    sector: 'financial_services',
    segment: 'Financial Services',
    employees: 800,
    headquarters: 'São Paulo, SP',
    states: ['SP'],
    cargoDiversity: 3,
    multiState: 2,
    unionActivity: 3,
    operationalRatio: 0.50,
    seniorityVariance: 4,
    recentLayoffs: 1,
    mAndA: 1,
    restructuring: 1,
    privatization: 0,
    notes: 'Promotora de crédito consignado, pequena',
  },
  {
    id: 'parana-banco',
    name: 'Paraná Banco',
    sector: 'financial_services',
    segment: 'Financial Services',
    employees: 800,
    headquarters: 'Curitiba, PR',
    states: ['PR', 'SP'],
    cargoDiversity: 3,
    multiState: 3,
    unionActivity: 4,
    operationalRatio: 0.40,
    seniorityVariance: 5,
    recentLayoffs: 1,
    mAndA: 1,
    restructuring: 1,
    privatization: 0,
    notes: 'Banco regional, crédito consignado',
  },

  // ═══════════════════════════════════════
  // TECH
  // ═══════════════════════════════════════
  {
    id: 'meta',
    name: 'Meta',
    sector: 'tech',
    segment: 'Tech',
    employees: 3000,
    headquarters: 'São Paulo, SP',
    states: ['SP'],
    cargoDiversity: 6,
    multiState: 2,
    unionActivity: 1,
    operationalRatio: 0.10,
    seniorityVariance: 4,
    recentLayoffs: 9,
    mAndA: 2,
    restructuring: 8,
    privatization: 0,
    notes: 'Layoffs massivos globais 2023-2024 (~20% da força), impacto direto na operação BR',
  },
  {
    id: 'uber',
    name: 'Uber',
    sector: 'tech',
    segment: 'Tech',
    employees: 1500,
    headquarters: 'São Paulo, SP',
    states: ['SP', 'RJ', 'MG', 'PR', 'BA', 'DF', 'CE', 'PE', 'RS', 'SC'],
    cargoDiversity: 5,
    multiState: 10,
    unionActivity: 6,
    operationalRatio: 0.25,
    seniorityVariance: 3,
    recentLayoffs: 5,
    mAndA: 2,
    restructuring: 4,
    privatization: 0,
    notes: 'Funcionários corporativos + risco gigante de vínculo empregatício com motoristas (~1M motoristas). Decisões judiciais recentes reconhecendo vínculo.',
  },
  {
    id: 'airbnb',
    name: 'Airbnb',
    sector: 'tech',
    segment: 'Tech',
    employees: 500,
    headquarters: 'São Paulo, SP',
    states: ['SP'],
    cargoDiversity: 4,
    multiState: 1,
    unionActivity: 1,
    operationalRatio: 0.10,
    seniorityVariance: 3,
    recentLayoffs: 4,
    mAndA: 1,
    restructuring: 3,
    privatization: 0,
    notes: 'Operação BR pequena, layoffs globais 2023',
  },
  {
    id: 'loft',
    name: 'Loft',
    sector: 'tech',
    segment: 'Tech',
    employees: 1000,
    headquarters: 'São Paulo, SP',
    states: ['SP', 'RJ'],
    cargoDiversity: 5,
    multiState: 3,
    unionActivity: 1,
    operationalRatio: 0.30,
    seniorityVariance: 3,
    recentLayoffs: 9,
    mAndA: 5,
    restructuring: 8,
    privatization: 0,
    notes: 'Layoffs massivos 2023 (>50% do quadro), pivot de modelo, múltiplas aquisições (CredPago, Vista)',
  },

  // ═══════════════════════════════════════
  // RETAIL
  // ═══════════════════════════════════════
  {
    id: 'mercado-livre',
    name: 'Mercado Livre',
    sector: 'retail',
    segment: 'Retail',
    employees: 40000,
    headquarters: 'São Paulo, SP',
    states: ['SP', 'RJ', 'MG', 'PR', 'RS', 'BA', 'PE', 'CE', 'SC', 'GO', 'DF'],
    cargoDiversity: 9,
    multiState: 10,
    unionActivity: 5,
    operationalRatio: 0.65,
    seniorityVariance: 6,
    recentLayoffs: 2,
    mAndA: 4,
    restructuring: 3,
    privatization: 0,
    notes: 'Crescimento explosivo de logística (Mercado Envios), milhares de operadores de CD. Contratação massiva → alta rotatividade.',
  },
  {
    id: 'ifood',
    name: 'iFood',
    sector: 'retail',
    segment: 'Retail',
    employees: 6000,
    headquarters: 'São Paulo, SP',
    states: ['SP', 'RJ', 'MG', 'PR', 'BA', 'DF', 'CE', 'PE', 'RS'],
    cargoDiversity: 6,
    multiState: 9,
    unionActivity: 4,
    operationalRatio: 0.30,
    seniorityVariance: 3,
    recentLayoffs: 7,
    mAndA: 3,
    restructuring: 5,
    privatization: 0,
    notes: 'Layoffs 2023-2024, risco de vínculo com entregadores (similar a Uber), centenas de milhares de entregadores',
  },
  {
    id: 'magalu',
    name: 'Magazine Luiza',
    sector: 'retail',
    segment: 'Retail',
    employees: 28000,
    headquarters: 'Franca, SP',
    states: ['SP', 'MG', 'RJ', 'PR', 'RS', 'BA', 'PE', 'CE', 'GO', 'DF', 'SC', 'MA', 'PA'],
    cargoDiversity: 8,
    multiState: 10,
    unionActivity: 6,
    operationalRatio: 0.70,
    seniorityVariance: 7,
    recentLayoffs: 6,
    mAndA: 5,
    restructuring: 6,
    privatization: 0,
    notes: 'Varejista com rede de lojas + CD + ecommerce. Demissões em massa 2023-2024 na operação de tech/ecommerce. Sindicato do comércio ativo.',
  },

  // ═══════════════════════════════════════
  // AIRLINES
  // ═══════════════════════════════════════
  {
    id: 'latam',
    name: 'LATAM Airlines Brasil',
    sector: 'airlines',
    segment: 'Airlines',
    employees: 20000,
    headquarters: 'São Paulo, SP',
    states: ['SP', 'RJ', 'MG', 'RS', 'PR', 'BA', 'DF', 'CE', 'PE', 'SC', 'PA', 'AM', 'GO'],
    cargoDiversity: 9,
    multiState: 10,
    unionActivity: 9,
    operationalRatio: 0.75,
    seniorityVariance: 8,
    recentLayoffs: 8,
    mAndA: 6,
    restructuring: 9,
    privatization: 0,
    notes: 'Recuperação judicial 2020-2022 → demissões massivas, corte de rotas, renegociação trabalhista. Sindicatos de pilotos, comissários e mecânicos são muito fortes.',
  },
  {
    id: 'azul',
    name: 'Azul Linhas Aéreas',
    sector: 'airlines',
    segment: 'Airlines',
    employees: 14000,
    headquarters: 'Barueri, SP',
    states: ['SP', 'RJ', 'MG', 'RS', 'PR', 'BA', 'DF', 'CE', 'PE', 'SC', 'PA', 'AM', 'GO'],
    cargoDiversity: 8,
    multiState: 10,
    unionActivity: 8,
    operationalRatio: 0.75,
    seniorityVariance: 7,
    recentLayoffs: 6,
    mAndA: 3,
    restructuring: 7,
    privatization: 0,
    notes: 'Reestruturação de dívida 2023-2024, negociação trabalhista com sindicatos, operação regional extensa',
  },

  // ═══════════════════════════════════════
  // TELECOM
  // ═══════════════════════════════════════
  {
    id: 'vivo',
    name: 'Vivo (Telefônica Brasil)',
    sector: 'telecom',
    segment: 'Telecom',
    employees: 33000,
    headquarters: 'São Paulo, SP',
    states: ['SP', 'RJ', 'MG', 'RS', 'PR', 'BA', 'PE', 'CE', 'DF', 'SC', 'GO', 'ES', 'PA', 'MA', 'AM'],
    cargoDiversity: 8,
    multiState: 10,
    unionActivity: 8,
    operationalRatio: 0.55,
    seniorityVariance: 8,
    recentLayoffs: 5,
    mAndA: 7,
    restructuring: 6,
    privatization: 4,
    notes: 'Absorveu parte da Oi. Terceirização massiva de técnicos de campo gera contencioso de vínculo. Sindicato SINTTEL forte.',
  },
  {
    id: 'nio',
    name: 'NIO',
    sector: 'telecom',
    segment: 'Telecom',
    employees: 1000,
    headquarters: 'São Paulo, SP',
    states: ['SP'],
    cargoDiversity: 4,
    multiState: 2,
    unionActivity: 3,
    operationalRatio: 0.30,
    seniorityVariance: 3,
    recentLayoffs: 2,
    mAndA: 1,
    restructuring: 2,
    privatization: 0,
    notes: 'Telecom menor, operação concentrada',
  },
  {
    id: 'tim',
    name: 'TIM Brasil',
    sector: 'telecom',
    segment: 'Telecom',
    employees: 10000,
    headquarters: 'Rio de Janeiro, RJ',
    states: ['RJ', 'SP', 'MG', 'RS', 'PR', 'BA', 'PE', 'CE', 'DF', 'SC', 'GO', 'PA'],
    cargoDiversity: 7,
    multiState: 10,
    unionActivity: 7,
    operationalRatio: 0.50,
    seniorityVariance: 7,
    recentLayoffs: 4,
    mAndA: 8,
    restructuring: 5,
    privatization: 0,
    notes: 'Comprou parte da Oi móvel em 2022, integração de funcionários em andamento, risco de equiparação salarial',
  },

  // ═══════════════════════════════════════
  // HEALTHCARE
  // ═══════════════════════════════════════
  {
    id: 'sulamerica',
    name: 'SulAmérica',
    sector: 'healthcare',
    segment: 'Healthcare',
    employees: 5000,
    headquarters: 'Rio de Janeiro, RJ',
    states: ['RJ', 'SP', 'MG', 'PR', 'RS', 'BA', 'DF'],
    cargoDiversity: 6,
    multiState: 7,
    unionActivity: 5,
    operationalRatio: 0.40,
    seniorityVariance: 6,
    recentLayoffs: 4,
    mAndA: 8,
    restructuring: 6,
    privatization: 0,
    notes: 'Adquirida pela Rede D\'Or em 2022 → integração de quadros, demissões de duplicação',
  },
  {
    id: 'hapvida',
    name: 'Hapvida',
    sector: 'healthcare',
    segment: 'Healthcare',
    employees: 68000,
    headquarters: 'Fortaleza, CE',
    states: ['CE', 'SP', 'RJ', 'MG', 'BA', 'PE', 'MA', 'PA', 'AM', 'GO', 'DF', 'PR', 'RS'],
    cargoDiversity: 9,
    multiState: 10,
    unionActivity: 7,
    operationalRatio: 0.80,
    seniorityVariance: 7,
    recentLayoffs: 5,
    mAndA: 10,
    restructuring: 8,
    privatization: 0,
    notes: 'Fusão Hapvida+NotreDame Intermédica 2022 = MAIOR operadora do Brasil. Integração massiva de 70k+ funcionários. Médicos, enfermeiros, técnicos. Contencioso trabalhista explosivo.',
  },

  // ═══════════════════════════════════════
  // UTILITIES
  // ═══════════════════════════════════════
  {
    id: 'light',
    name: 'Light',
    sector: 'utilities',
    segment: 'Utilities',
    employees: 4000,
    headquarters: 'Rio de Janeiro, RJ',
    states: ['RJ'],
    cargoDiversity: 7,
    multiState: 2,
    unionActivity: 8,
    operationalRatio: 0.65,
    seniorityVariance: 8,
    recentLayoffs: 6,
    mAndA: 2,
    restructuring: 8,
    privatization: 3,
    notes: 'Recuperação judicial 2023, demissões, sindicato dos eletricitários muito forte, periculosidade',
  },
  {
    id: 'energisa',
    name: 'Energisa',
    sector: 'utilities',
    segment: 'Utilities',
    employees: 18000,
    headquarters: 'Cataguases, MG',
    states: ['MG', 'MT', 'MS', 'TO', 'PB', 'SE', 'AC', 'RO', 'RR', 'SP'],
    cargoDiversity: 7,
    multiState: 10,
    unionActivity: 7,
    operationalRatio: 0.70,
    seniorityVariance: 7,
    recentLayoffs: 3,
    mAndA: 7,
    restructuring: 4,
    privatization: 5,
    notes: 'Crescimento agressivo por aquisições de distribuidoras, presença em estados remotos, trabalho de campo perigoso',
  },

  // ═══════════════════════════════════════
  // SERVICES
  // ═══════════════════════════════════════
  {
    id: 'verzani-sandrini',
    name: 'Verzani & Sandrini',
    sector: 'services',
    segment: 'Services',
    employees: 45000,
    headquarters: 'São Paulo, SP',
    states: ['SP', 'RJ', 'MG', 'PR', 'RS', 'BA', 'PE', 'DF', 'GO', 'SC', 'CE'],
    cargoDiversity: 6,
    multiState: 10,
    unionActivity: 6,
    operationalRatio: 0.90,
    seniorityVariance: 5,
    recentLayoffs: 3,
    mAndA: 4,
    restructuring: 3,
    privatization: 0,
    notes: 'Facilities management (limpeza, segurança, portaria). 90% da força é operacional com altíssima rotatividade. Contencioso massivo por natureza.',
  },
  {
    id: 'aec',
    name: 'AeC',
    sector: 'services',
    segment: 'Services',
    employees: 45000,
    headquarters: 'Belo Horizonte, MG',
    states: ['MG', 'SP', 'BA', 'PE', 'PB', 'SE', 'CE'],
    cargoDiversity: 4,
    multiState: 8,
    unionActivity: 5,
    operationalRatio: 0.92,
    seniorityVariance: 3,
    recentLayoffs: 4,
    mAndA: 3,
    restructuring: 3,
    privatization: 0,
    notes: 'Call center / BPO. Rotatividade extrema (~60% ao ano), alto volume de ações por hora extra, DORT/LER, assédio moral. Uma das maiores geradoras de contencioso trabalhista do Brasil.',
  },
];

export function getCompanyById(id) {
  return companies.find((c) => c.id === id) || null;
}

export function getCompaniesBySegment(segment) {
  return companies.filter((c) => c.segment === segment);
}
