/**
 * Enter client base — all companies with researched labor risk factors.
 *
 * Sources (March 2026):
 *  - Employee counts: CVM filings, SEC 20-F, annual reports, DIEESE
 *  - Layoff/M&A data: Contraf-CUT, SINTETEL, SNA, SIEMACO, news
 *  - Union activity: Sindicato dos Bancários SP, SINTERGIA, SNA, SINDPD
 *  - TST Ranking das Partes, CNJ Justiça em Números 2025
 *
 * Key: Itaú had 14,818 active labor cases (TST 2015 baseline)
 *       Top 100 companies avg 4,315 cases each (13.6% of all cases)
 *       R$50.6B paid by employers in labor lawsuits in 2025 (record)
 */

export const companies = [
  // ═══════════════════════════════════════
  // FINANCIAL SERVICES
  // ═══════════════════════════════════════
  {
    id: 'nubank',
    name: 'Nubank',
    sector: 'financial_services',
    segment: 'Financial Services',
    employees: 8716,  // FY2024 global, ~7k BR-based
    headquarters: 'São Paulo, SP',
    states: ['SP', 'RJ', 'MG', 'PE', 'DF'],
    cargoDiversity: 6,
    multiState: 5,
    unionActivity: 5,  // ↑ SEEB-SP formally engaged; 12-14 justa causa dismissals Nov 2025 after RTO opposition
    operationalRatio: 0.30,
    seniorityVariance: 4,
    recentLayoffs: 7,  // ↑ justa causa dismissals for opposing RTO policy; 20% turnover 2023 (~1,180/yr)
    mAndA: 2,
    restructuring: 5,  // ↑ mandatory return-to-office triggered manifesto from 300 employees
    privatization: 0,
    notes: 'Nov 2025: 12-14 dismissed por justa causa após oposição ao RTO — retaliação sindical exposure. Turnover 20% em 2023. SEEB-SP/Osasco cobre Nubank. 114M clientes.',
  },
  {
    id: 'santander',
    name: 'Santander Brasil',
    sector: 'financial_services',
    segment: 'Financial Services',
    employees: 55646,  // FY2024 consolidated
    headquarters: 'São Paulo, SP',
    states: ['SP', 'RJ', 'MG', 'RS', 'PR', 'BA', 'PE', 'CE', 'DF', 'SC', 'GO', 'ES'],
    cargoDiversity: 8,
    multiState: 10,
    unionActivity: 10,  // ↑ Contraf-CUT jornada internacional de luta; bancários fecham agências em protesto
    operationalRatio: 0.55,
    seniorityVariance: 8,
    recentLayoffs: 6,  // ↑ 15+ demissões/mês em alguns estados; proporção feminina caiu 59%→43%
    mAndA: 3,
    restructuring: 6,  // ↑ reestruturação sem diálogo sindical; discriminação de gênero documentada
    privatization: 0,
    notes: 'Reestruturação sem aviso ao sindicato. Contraf-CUT coordenação internacional. Proporção feminina caiu 59%→43% = exposição discriminação gênero. 15+ demissões/mês reportadas.',
  },
  {
    id: 'itau',
    name: 'Itaú Unibanco',
    sector: 'financial_services',
    segment: 'Financial Services',
    employees: 96219,  // FY2024 consolidated, ~88k BR
    headquarters: 'São Paulo, SP',
    states: ['SP', 'RJ', 'MG', 'RS', 'PR', 'BA', 'PE', 'CE', 'DF', 'SC', 'GO', 'ES', 'PA', 'MA'],
    cargoDiversity: 9,
    multiState: 10,
    unionActivity: 9,
    operationalRatio: 0.50,
    seniorityVariance: 9,
    recentLayoffs: 8,  // ↑ ~1,000 demissões Set/2025 por monitoramento de produtividade home office. TRT-SP ação.
    mAndA: 7,
    restructuring: 7,
    privatization: 0,
    notes: 'TST 2015: 14,818 ações ativas. Set/2025: ~1,000 demitidos por keystroke monitoring (home office). Sindicato levou ao TRT-SP, acordo 4-6 meses salário + R$9k. Provisão total ~R$36.2B. Maior banco privado BR.',
  },
  {
    id: 'bradesco',
    name: 'Bradesco',
    sector: 'financial_services',
    segment: 'Financial Services',
    employees: 84022,  // FY2024 consolidated holding; 72,642 Banco Bradesco
    headquarters: 'Osasco, SP',
    states: ['SP', 'RJ', 'MG', 'RS', 'PR', 'BA', 'PE', 'CE', 'DF', 'SC', 'GO', 'ES', 'PA'],
    cargoDiversity: 9,
    multiState: 10,
    unionActivity: 9,
    operationalRatio: 0.50,
    seniorityVariance: 9,
    recentLayoffs: 8,  // ↑ 2,200 demissões FY2024; 390 agências + 903 pontos + 92 UNs fechadas
    mAndA: 5,
    restructuring: 9,  // ↑ PDV lançado; R$570M provisão especial para reestruturação
    privatization: 0,
    notes: 'TST 2015: 11,316 ações. FY2024: 2,200 demissões, PDV, R$570M provisão reestruturação. CEO Noronha acelerou digitalização. Ratio cliente/func subiu (1,298 vs 1,227) = risco overwork.',
  },
  {
    id: 'c6bank',
    name: 'C6 Bank',
    sector: 'financial_services',
    segment: 'Financial Services',
    employees: 5500,
    headquarters: 'São Paulo, SP',
    states: ['SP', 'RJ'],
    cargoDiversity: 5,
    multiState: 3,
    unionActivity: 2,
    operationalRatio: 0.30,
    seniorityVariance: 3,
    recentLayoffs: 6,
    mAndA: 2,
    restructuring: 4,
    privatization: 0,
    notes: 'Layoffs significativos 2023, JP Morgan como acionista',
  },
  {
    id: 'banco-volkswagen',
    name: 'Banco Volkswagen',
    sector: 'financial_services',
    segment: 'Financial Services',
    employees: 1200,
    headquarters: 'São Paulo, SP',
    states: ['SP'],
    cargoDiversity: 4,
    multiState: 2,
    unionActivity: 5,
    operationalRatio: 0.30,
    seniorityVariance: 6,
    recentLayoffs: 2,
    mAndA: 3,
    restructuring: 2,
    privatization: 0,
    notes: 'Banco cativo, ligado à VW do Brasil com sindicato metalúrgico forte',
  },
  {
    id: 'banco-pan',
    name: 'Banco Pan',
    sector: 'financial_services',
    segment: 'Financial Services',
    employees: 4500,
    headquarters: 'São Paulo, SP',
    states: ['SP', 'RJ', 'MG', 'PR'],
    cargoDiversity: 5,
    multiState: 5,
    unionActivity: 5,
    operationalRatio: 0.45,
    seniorityVariance: 5,
    recentLayoffs: 3,
    mAndA: 4,
    restructuring: 3,
    privatization: 0,
    notes: 'Controlado pelo BTG Pactual, foco em crédito consignado',
  },
  {
    id: 'agi',
    name: 'Agi (Agibank)',
    sector: 'financial_services',
    segment: 'Financial Services',
    employees: 3000,
    headquarters: 'Porto Alegre, RS',
    states: ['RS', 'SP', 'MG'],
    cargoDiversity: 5,
    multiState: 4,
    unionActivity: 4,
    operationalRatio: 0.50,
    seniorityVariance: 4,
    recentLayoffs: 3,
    mAndA: 2,
    restructuring: 3,
    privatization: 0,
    notes: 'Rede de agências físicas para público C/D, alta rotatividade de gerentes',
  },
  {
    id: 'inter',
    name: 'Inter (Banco Inter)',
    sector: 'financial_services',
    segment: 'Financial Services',
    employees: 4000,
    headquarters: 'Belo Horizonte, MG',
    states: ['MG', 'SP'],
    cargoDiversity: 5,
    multiState: 3,
    unionActivity: 3,
    operationalRatio: 0.30,
    seniorityVariance: 3,
    recentLayoffs: 4,
    mAndA: 3,
    restructuring: 3,
    privatization: 0,
    notes: 'IPO na Nasdaq, crescimento acelerado, cultura de startup',
  },
  {
    id: 'bv',
    name: 'BV (Banco Votorantim)',
    sector: 'financial_services',
    segment: 'Financial Services',
    employees: 3500,
    headquarters: 'São Paulo, SP',
    states: ['SP', 'RJ', 'MG', 'PR'],
    cargoDiversity: 5,
    multiState: 5,
    unionActivity: 5,
    operationalRatio: 0.40,
    seniorityVariance: 6,
    recentLayoffs: 2,
    mAndA: 2,
    restructuring: 2,
    privatization: 0,
    notes: 'Joint venture Votorantim + Banco do Brasil, estável',
  },
  {
    id: 'banco-mercantil',
    name: 'Banco Mercantil',
    sector: 'financial_services',
    segment: 'Financial Services',
    employees: 3000,
    headquarters: 'Belo Horizonte, MG',
    states: ['MG', 'SP', 'RJ', 'BA'],
    cargoDiversity: 5,
    multiState: 5,
    unionActivity: 5,
    operationalRatio: 0.50,
    seniorityVariance: 7,
    recentLayoffs: 3,
    mAndA: 1,
    restructuring: 3,
    privatization: 0,
    notes: 'Banco tradicional, foco em aposentados/INSS, funcionários com alta antiguidade',
  },
  {
    id: 'banco-daycoval',
    name: 'Banco Daycoval',
    sector: 'financial_services',
    segment: 'Financial Services',
    employees: 2000,
    headquarters: 'São Paulo, SP',
    states: ['SP', 'RJ'],
    cargoDiversity: 4,
    multiState: 3,
    unionActivity: 4,
    operationalRatio: 0.35,
    seniorityVariance: 5,
    recentLayoffs: 2,
    mAndA: 1,
    restructuring: 1,
    privatization: 0,
    notes: 'Middle market, estável',
  },
  {
    id: 'bmg',
    name: 'Banco BMG',
    sector: 'financial_services',
    segment: 'Financial Services',
    employees: 3500,
    headquarters: 'Belo Horizonte, MG',
    states: ['MG', 'SP', 'RJ', 'BA', 'PE'],
    cargoDiversity: 5,
    multiState: 6,
    unionActivity: 5,
    operationalRatio: 0.50,
    seniorityVariance: 6,
    recentLayoffs: 4,
    mAndA: 2,
    restructuring: 4,
    privatization: 0,
    notes: 'Crédito consignado, reestruturação digital em andamento',
  },
  {
    id: 'uol',
    name: 'UOL (PagSeguro/PagBank)',
    sector: 'financial_services',
    segment: 'Financial Services',
    employees: 7000,
    headquarters: 'São Paulo, SP',
    states: ['SP', 'RJ', 'MG', 'PR', 'SC'],
    cargoDiversity: 6,
    multiState: 6,
    unionActivity: 3,
    operationalRatio: 0.40,
    seniorityVariance: 4,
    recentLayoffs: 5,
    mAndA: 4,
    restructuring: 5,
    privatization: 0,
    notes: 'Grupo UOL/PagSeguro, layoffs em tech, múltiplas subsidiárias',
  },
  {
    id: 'omni',
    name: 'Omni',
    sector: 'financial_services',
    segment: 'Financial Services',
    employees: 1500,
    headquarters: 'São Paulo, SP',
    states: ['SP', 'RJ'],
    cargoDiversity: 4,
    multiState: 3,
    unionActivity: 4,
    operationalRatio: 0.40,
    seniorityVariance: 5,
    recentLayoffs: 2,
    mAndA: 1,
    restructuring: 2,
    privatization: 0,
    notes: 'Financeira focada em veículos',
  },
  {
    id: 'recovery',
    name: 'Recovery',
    sector: 'financial_services',
    segment: 'Financial Services',
    employees: 2500,
    headquarters: 'São Paulo, SP',
    states: ['SP', 'RJ', 'MG'],
    cargoDiversity: 4,
    multiState: 4,
    unionActivity: 3,
    operationalRatio: 0.60,
    seniorityVariance: 4,
    recentLayoffs: 3,
    mAndA: 3,
    restructuring: 3,
    privatization: 0,
    notes: 'Cobrança e recuperação de crédito, alta rotatividade de operadores',
  },
  {
    id: 'bem-promotora',
    name: 'Bem Promotora',
    sector: 'financial_services',
    segment: 'Financial Services',
    employees: 800,
    headquarters: 'São Paulo, SP',
    states: ['SP'],
    cargoDiversity: 3,
    multiState: 2,
    unionActivity: 3,
    operationalRatio: 0.50,
    seniorityVariance: 4,
    recentLayoffs: 1,
    mAndA: 1,
    restructuring: 1,
    privatization: 0,
    notes: 'Promotora de crédito consignado, pequena',
  },
  {
    id: 'parana-banco',
    name: 'Paraná Banco',
    sector: 'financial_services',
    segment: 'Financial Services',
    employees: 800,
    headquarters: 'Curitiba, PR',
    states: ['PR', 'SP'],
    cargoDiversity: 3,
    multiState: 3,
    unionActivity: 4,
    operationalRatio: 0.40,
    seniorityVariance: 5,
    recentLayoffs: 1,
    mAndA: 1,
    restructuring: 1,
    privatization: 0,
    notes: 'Banco regional, crédito consignado',
  },

  // ═══════════════════════════════════════
  // TECH
  // ═══════════════════════════════════════
  {
    id: 'meta',
    name: 'Meta',
    sector: 'tech',
    segment: 'Tech',
    employees: 3000,
    headquarters: 'São Paulo, SP',
    states: ['SP'],
    cargoDiversity: 6,
    multiState: 2,
    unionActivity: 1,
    operationalRatio: 0.10,
    seniorityVariance: 4,
    recentLayoffs: 9,
    mAndA: 2,
    restructuring: 8,
    privatization: 0,
    notes: 'Layoffs massivos globais 2023-2024 (~20% da força), impacto direto na operação BR',
  },
  {
    id: 'uber',
    name: 'Uber',
    sector: 'tech',
    segment: 'Tech',
    employees: 1500,
    headquarters: 'São Paulo, SP',
    states: ['SP', 'RJ', 'MG', 'PR', 'BA', 'DF', 'CE', 'PE', 'RS', 'SC'],
    cargoDiversity: 5,
    multiState: 10,
    unionActivity: 6,
    operationalRatio: 0.25,
    seniorityVariance: 3,
    recentLayoffs: 5,
    mAndA: 2,
    restructuring: 4,
    privatization: 0,
    notes: 'Funcionários corporativos + risco gigante de vínculo empregatício com motoristas (~1M motoristas). Decisões judiciais recentes reconhecendo vínculo.',
  },
  {
    id: 'airbnb',
    name: 'Airbnb',
    sector: 'tech',
    segment: 'Tech',
    employees: 500,
    headquarters: 'São Paulo, SP',
    states: ['SP'],
    cargoDiversity: 4,
    multiState: 1,
    unionActivity: 1,
    operationalRatio: 0.10,
    seniorityVariance: 3,
    recentLayoffs: 4,
    mAndA: 1,
    restructuring: 3,
    privatization: 0,
    notes: 'Operação BR pequena, layoffs globais 2023',
  },
  {
    id: 'loft',
    name: 'Loft',
    sector: 'tech',
    segment: 'Tech',
    employees: 1000,
    headquarters: 'São Paulo, SP',
    states: ['SP', 'RJ'],
    cargoDiversity: 5,
    multiState: 3,
    unionActivity: 1,
    operationalRatio: 0.30,
    seniorityVariance: 3,
    recentLayoffs: 9,
    mAndA: 5,
    restructuring: 8,
    privatization: 0,
    notes: 'Layoffs massivos 2023 (>50% do quadro), pivot de modelo, múltiplas aquisições (CredPago, Vista)',
  },

  // ═══════════════════════════════════════
  // RETAIL
  // ═══════════════════════════════════════
  {
    id: 'mercado-livre',
    name: 'Mercado Livre',
    sector: 'retail',
    segment: 'Retail',
    employees: 33000,  // ~33k BR mid-2024; R$23B invested in BR 2024, R$57B planned 2026
    headquarters: 'São Paulo, SP',
    states: ['SP', 'RJ', 'MG', 'PR', 'RS', 'BA', 'PE', 'CE', 'SC', 'GO', 'DF'],
    cargoDiversity: 9,
    multiState: 10,
    unionActivity: 7,  // ↑ anti-union posture documented: fired employees after organizing assembly; SINDPD-SC cases
    operationalRatio: 0.60,
    seniorityVariance: 6,
    recentLayoffs: 5,  // ↑ Jan/2025: 118 LATAM-wide (38 BR), AI restructuring; 119 earlier for AI role elimination
    mAndA: 4,
    restructuring: 4,  // anti-union conduct; NDA/silence clauses on dismissed workers challenged
    privatization: 0,
    notes: 'Enter client (confirmed). Postura anti-sindical documentada (SINDPD-SC). Jan/2025: 38 BR demitidos por IA. STF courier classification looming. 21 CDs. R$57B investidos BR 2026.',
  },
  {
    id: 'ifood',
    name: 'iFood',
    sector: 'retail',
    segment: 'Retail',
    employees: 6000,
    headquarters: 'São Paulo, SP',
    states: ['SP', 'RJ', 'MG', 'PR', 'BA', 'DF', 'CE', 'PE', 'RS'],
    cargoDiversity: 6,
    multiState: 9,
    unionActivity: 4,
    operationalRatio: 0.30,
    seniorityVariance: 3,
    recentLayoffs: 7,
    mAndA: 3,
    restructuring: 5,
    privatization: 0,
    notes: 'Layoffs 2023-2024, risco de vínculo com entregadores (similar a Uber), centenas de milhares de entregadores',
  },
  {
    id: 'magalu',
    name: 'Magazine Luiza',
    sector: 'retail',
    segment: 'Retail',
    employees: 28000,
    headquarters: 'Franca, SP',
    states: ['SP', 'MG', 'RJ', 'PR', 'RS', 'BA', 'PE', 'CE', 'GO', 'DF', 'SC', 'MA', 'PA'],
    cargoDiversity: 8,
    multiState: 10,
    unionActivity: 6,
    operationalRatio: 0.70,
    seniorityVariance: 7,
    recentLayoffs: 6,
    mAndA: 5,
    restructuring: 6,
    privatization: 0,
    notes: 'Varejista com rede de lojas + CD + ecommerce. Demissões em massa 2023-2024 na operação de tech/ecommerce. Sindicato do comércio ativo.',
  },

  // ═══════════════════════════════════════
  // AIRLINES
  // ═══════════════════════════════════════
  {
    id: 'latam',
    name: 'LATAM Airlines Brasil',
    sector: 'airlines',
    segment: 'Airlines',
    employees: 22500,  // ~20,500 mid-2024 + 14% growth; ~22,500 by early 2025
    headquarters: 'São Paulo, SP',
    states: ['SP', 'RJ', 'MG', 'RS', 'PR', 'BA', 'DF', 'CE', 'PE', 'SC', 'PA', 'AM', 'GO'],
    cargoDiversity: 9,
    multiState: 10,
    unionActivity: 10,  // ↑ SNA (Aeronautas) very active; TST actions on folga social
    operationalRatio: 0.75,
    seniorityVariance: 8,
    recentLayoffs: 7,  // growth phase now but 2020 crisis layoffs still generating claims (2,743 tripulantes + 1,200)
    mAndA: 6,
    restructuring: 8,  // Chapter 11 exit 2022; R$4B government investment 2026
    privatization: 0,
    notes: 'Enter client (confirmed). 30% win rate increase com Enter (consumer). SNA muito ativo. Crise 2020: 2,743 tripulantes + 1,200 demitidos — ações ainda no pipeline. 60 destinos, 776 voos/dia.',
  },
  {
    id: 'azul',
    name: 'Azul Linhas Aéreas',
    sector: 'airlines',
    segment: 'Airlines',
    employees: 15400,  // FY2024 estimate
    headquarters: 'Barueri, SP',
    states: ['SP', 'RJ', 'MG', 'RS', 'PR', 'BA', 'DF', 'CE', 'PE', 'SC', 'PA', 'AM', 'GO'],
    cargoDiversity: 8,
    multiState: 10,
    unionActivity: 10,  // ↑ SNA acionou TST para bloquear 3,810 demissões; pilotos em estado de greve Dez/2025
    operationalRatio: 0.75,
    seniorityVariance: 7,
    recentLayoffs: 9,  // ↑ 3,810 demissões planejadas, 500+ aeroviários já demitidos; 113 pilotos saíram 2024
    mAndA: 3,
    restructuring: 10,  // ↑ Chapter 11 (Mai/2025 - Fev/2026), US$2.5B dívida eliminada
    privatization: 0,
    notes: 'Chapter 11 Mai/2025–Fev/2026. SNA acionou TST: 3,810 demissões. 500+ aeroviários demitidos. 113 pilotos saíram 2024 (48 só em Set/2025). Estado de greve Dez/2025. ~150 destinos.',
  },

  // ═══════════════════════════════════════
  // TELECOM
  // ═══════════════════════════════════════
  {
    id: 'vivo',
    name: 'Vivo (Telefônica Brasil)',
    sector: 'telecom',
    segment: 'Telecom',
    employees: 33000,
    headquarters: 'São Paulo, SP',
    states: ['SP', 'RJ', 'MG', 'RS', 'PR', 'BA', 'PE', 'CE', 'DF', 'SC', 'GO', 'ES', 'PA', 'MA', 'AM'],
    cargoDiversity: 8,
    multiState: 10,
    unionActivity: 8,
    operationalRatio: 0.55,
    seniorityVariance: 8,
    recentLayoffs: 5,
    mAndA: 7,
    restructuring: 6,
    privatization: 4,
    notes: 'Absorveu parte da Oi. Terceirização massiva de técnicos de campo gera contencioso de vínculo. Sindicato SINTTEL forte.',
  },
  {
    id: 'nio',
    name: 'NIO',
    sector: 'telecom',
    segment: 'Telecom',
    employees: 1000,
    headquarters: 'São Paulo, SP',
    states: ['SP'],
    cargoDiversity: 4,
    multiState: 2,
    unionActivity: 3,
    operationalRatio: 0.30,
    seniorityVariance: 3,
    recentLayoffs: 2,
    mAndA: 1,
    restructuring: 2,
    privatization: 0,
    notes: 'Telecom menor, operação concentrada',
  },
  {
    id: 'tim',
    name: 'TIM Brasil',
    sector: 'telecom',
    segment: 'Telecom',
    employees: 10000,
    headquarters: 'Rio de Janeiro, RJ',
    states: ['RJ', 'SP', 'MG', 'RS', 'PR', 'BA', 'PE', 'CE', 'DF', 'SC', 'GO', 'PA'],
    cargoDiversity: 7,
    multiState: 10,
    unionActivity: 7,
    operationalRatio: 0.50,
    seniorityVariance: 7,
    recentLayoffs: 4,
    mAndA: 8,
    restructuring: 5,
    privatization: 0,
    notes: 'Comprou parte da Oi móvel em 2022, integração de funcionários em andamento, risco de equiparação salarial',
  },

  // ═══════════════════════════════════════
  // HEALTHCARE
  // ═══════════════════════════════════════
  {
    id: 'sulamerica',
    name: 'SulAmérica',
    sector: 'healthcare',
    segment: 'Healthcare',
    employees: 5000,
    headquarters: 'Rio de Janeiro, RJ',
    states: ['RJ', 'SP', 'MG', 'PR', 'RS', 'BA', 'DF'],
    cargoDiversity: 6,
    multiState: 7,
    unionActivity: 5,
    operationalRatio: 0.40,
    seniorityVariance: 6,
    recentLayoffs: 4,
    mAndA: 8,
    restructuring: 6,
    privatization: 0,
    notes: 'Adquirida pela Rede D\'Or em 2022 → integração de quadros, demissões de duplicação',
  },
  {
    id: 'hapvida',
    name: 'Hapvida',
    sector: 'healthcare',
    segment: 'Healthcare',
    employees: 69000,  // 69k diretos + 28k médicos (2024)
    headquarters: 'Fortaleza, CE',
    states: ['CE', 'SP', 'RJ', 'MG', 'BA', 'PE', 'MA', 'PA', 'AM', 'GO', 'DF', 'PR', 'RS'],
    cargoDiversity: 10,  // ↑ médicos, enfermeiros, técnicos, admin, suporte — maior diversidade da base
    multiState: 10,
    unionActivity: 8,  // ↑ múltiplos sindicatos por profissão: SINDMED, SIPD, admin
    operationalRatio: 0.80,
    seniorityVariance: 7,
    recentLayoffs: 5,
    mAndA: 10,
    restructuring: 9,  // ↑ ANS investigando balanços desde 2024; financial distress; integração NDI incompleta
    privatization: 0,
    notes: 'MAIOR operadora BR. Fusão Hapvida+NDI 2022: 69k+28k médicos. ANS investigando balanços. 86 hospitais, 77 UPAs, 341 clínicas. Insalubridade +1,092% no TST 2024. Provisões possivelmente underfunded.',
  },

  // ═══════════════════════════════════════
  // UTILITIES
  // ═══════════════════════════════════════
  {
    id: 'light',
    name: 'Light',
    sector: 'utilities',
    segment: 'Utilities',
    employees: 4000,
    headquarters: 'Rio de Janeiro, RJ',
    states: ['RJ'],
    cargoDiversity: 7,
    multiState: 2,
    unionActivity: 8,
    operationalRatio: 0.65,
    seniorityVariance: 8,
    recentLayoffs: 6,
    mAndA: 2,
    restructuring: 8,
    privatization: 3,
    notes: 'Recuperação judicial 2023, demissões, sindicato dos eletricitários muito forte, periculosidade',
  },
  {
    id: 'energisa',
    name: 'Energisa',
    sector: 'utilities',
    segment: 'Utilities',
    employees: 18000,
    headquarters: 'Cataguases, MG',
    states: ['MG', 'MT', 'MS', 'TO', 'PB', 'SE', 'AC', 'RO', 'RR', 'SP'],
    cargoDiversity: 7,
    multiState: 10,
    unionActivity: 7,
    operationalRatio: 0.70,
    seniorityVariance: 7,
    recentLayoffs: 3,
    mAndA: 7,
    restructuring: 4,
    privatization: 5,
    notes: 'Crescimento agressivo por aquisições de distribuidoras, presença em estados remotos, trabalho de campo perigoso',
  },

  // ═══════════════════════════════════════
  // SERVICES
  // ═══════════════════════════════════════
  {
    id: 'verzani-sandrini',
    name: 'Verzani & Sandrini',
    sector: 'services',
    segment: 'Services',
    employees: 45000,
    headquarters: 'São Paulo, SP',
    states: ['SP', 'RJ', 'MG', 'PR', 'RS', 'BA', 'PE', 'DF', 'GO', 'SC', 'CE'],
    cargoDiversity: 6,
    multiState: 10,
    unionActivity: 6,
    operationalRatio: 0.90,
    seniorityVariance: 5,
    recentLayoffs: 3,
    mAndA: 4,
    restructuring: 3,
    privatization: 0,
    notes: 'Facilities management (limpeza, segurança, portaria). 90% da força é operacional com altíssima rotatividade. Contencioso massivo por natureza.',
  },
  {
    id: 'aec',
    name: 'AeC',
    sector: 'services',
    segment: 'Services',
    employees: 30000,  // estimated from R$2B revenue + labor intensity
    headquarters: 'Belo Horizonte, MG',
    states: ['MG', 'SP', 'BA', 'PE', 'PB', 'SE', 'CE'],
    cargoDiversity: 4,
    multiState: 8,
    unionActivity: 6,  // ↑ primeira mobilização coletiva formal em 2025; SINTELMARK
    operationalRatio: 0.90,
    seniorityVariance: 3,
    recentLayoffs: 5,
    mAndA: 3,
    restructuring: 4,  // ↑ documented CLT violations: Art. 386 (women scheduled every Sunday)
    privatization: 0,
    notes: 'Call center #1 para volume TST. Violações documentadas: Art. 386 CLT, recusa a assinar rescisão. Primeira negociação coletiva formal 2025. TRT CG (PB) ação de demissão em massa. DORT/LER endêmico.',
  },
];

export function getCompanyById(id) {
  return companies.find((c) => c.id === id) || null;
}

export function getCompaniesBySegment(segment) {
  return companies.filter((c) => c.segment === segment);
}
